= Preface

== Who this book is for
This book is for developers who want to build robust REST APIs using Spring Boot. Both beginner and experienced developers can benefit from this book.

== What you need for this book

To try code samples in this book, you will need a computer running an up-to-date operating system (Windows, Linux, or Mac OS X). You will need Java 17 and MongoDB installed. The book code was tested against JDK 17, but newer versions should also work.

== Conventions

We use a number of typographical conventions within this book that distinguish between different kinds of information.

Code in the text, including commands, variables, file names, CSS class names, and property names are shown as follows:

[example]
Spring Boot uses a `public static void main` entry-point that launches an embedded web server for you.

A block of code is set out as follows. It may be colored, depending on the format in which you're reading this book.

[source,java]
.src/main/java/demo/DemoApplication.java
----
@RestController
class BlogController {
    private final BlogRepository repository;

    // Yay! No annotations needed for constructor injection in Spring 4.3+.
    public BlogController(BlogRepository repository) {
        this.repository = repository;
    }

    @RequestMapping("/blogs")
    Collection<Blog> list() {
        return repository.findAll();
    }
}
----

When we want to draw your attention to certain lines of code, those lines are annotated using numbers accompanied by brief descriptions.

[source,java]
----
@RestController <1>
class BlogController {
    private final BlogRepository repository;

    public BlogController(BlogRepository repository) { <2>
        this.repository = repository;
    }

    @GetMapping("/blogs") <3>
    Collection<Blog> list() {
        return repository.findAll();
    }
}
----
<1> The `BlogController` class is annotated with the `@RestController` annotation indicating that it is a Spring Controller which handles the REST Based Requests from the Client.
<2> We are injecting the `BlogRepository` class into the `BlogController` class through `Constructor Injection`.
<3> The `@GetMapping` annotation is responsible to define an HTTP GET Endpoint at the url - `/blogs`

TIP: Tips are shown using callouts like this.

WARNING: Warnings are shown using callouts like this.

.Sidebar
****
Additional information about a certain topic may be displayed in a sidebar like this one.
****

Finally, this text shows what a quote looks like:

"In the end, it's not the years in your life that count. It's the life in your years."
-- Abraham Lincoln

== Reader feedback

Let me know what you thought about this book — what you liked or disliked. Reader feedback helps me develop more ebooks and content that deliver the most value to you.

[.text-left]
To send us feedback, e-mail us at programmingtechie@gmail.com, send a tweet to @sai90_u (https://twitter.com/sai90_u).
